CREATE TABLE IF NOT EXISTS "GroupLoanPolicy" (
  "groupId" TEXT NOT NULL,
  "savingsMultiplierBps" INTEGER NOT NULL DEFAULT 20000,
  "monthlyInterestRateBps" INTEGER NOT NULL DEFAULT 150,
  "processingFeeBps" INTEGER NOT NULL DEFAULT 200,
  "minimumGuarantors" INTEGER NOT NULL DEFAULT 1,
  "maximumTermMonths" INTEGER NOT NULL DEFAULT 60,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "GroupLoanPolicy_pkey" PRIMARY KEY ("groupId"),
  CONSTRAINT "GroupLoanPolicy_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "Group"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

ALTER TABLE "LoanApplication"
ADD COLUMN IF NOT EXISTS "processingFeeBps" INTEGER NOT NULL DEFAULT 200;

ALTER TABLE "LoanApplication"
ADD COLUMN IF NOT EXISTS "requiredGuarantors" INTEGER NOT NULL DEFAULT 1;

ALTER TABLE "GroupLoan"
ADD COLUMN IF NOT EXISTS "processingFeeBps" INTEGER NOT NULL DEFAULT 200;
