ALTER TYPE "ContributionFrequency" ADD VALUE IF NOT EXISTS 'DAILY';
ALTER TYPE "ContributionFrequency" ADD VALUE IF NOT EXISTS 'WEEKLY';

ALTER TABLE "Group" ADD COLUMN IF NOT EXISTS "establishedAt" TIMESTAMP(3);
ALTER TABLE "Group" ADD COLUMN IF NOT EXISTS "historicalDataStartsAt" TIMESTAMP(3);

ALTER TABLE "ContributionPlan" ADD COLUMN IF NOT EXISTS "dueDayOfWeek" INTEGER;
ALTER TABLE "ContributionPlan" ADD COLUMN IF NOT EXISTS "dueDayOfMonth" INTEGER;
ALTER TABLE "ContributionPlan" ADD COLUMN IF NOT EXISTS "cycleAnchorDate" TIMESTAMP(3);

ALTER TABLE "GroupContributionPayment" ADD COLUMN IF NOT EXISTS "paidAt" TIMESTAMP(3);
