ALTER TABLE "ReminderCampaign" ADD COLUMN IF NOT EXISTS "body" TEXT NOT NULL DEFAULT '';
ALTER TABLE "ReminderCampaign" ADD COLUMN IF NOT EXISTS "recipientCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ReminderCampaign" ADD COLUMN IF NOT EXISTS "createdByUserId" TEXT;
